version: '3'

services:

  mysql:
    image: mysql:5.7
    environment:
      - "MYSQL_RANDOM_ROOT_PASSWORD=${MYSQL_RANDOM_ROOT_PASSWORD}"
      - "MYSQL_DATABASE=${DB_NAME}"
      - "MYSQL_USER=${DB_USER}"
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
    volumes:
      - mysql_data:/var/lib/mysql:delegated

  app:
    build:  ./docker/app
    volumes:
      - ./docker/app/conf/sites-available:/etc/apache2/sites-available
      - .:/var/www/html:cached
    ports:
      - 8000:80
    environment:
      PHP_IDE_CONFIG: serverName=wcf.dev
    depends_on:
      - mysql

volumes:
  mysql_data: ~